layout_spectrum: 0.9247312
color:
  saturation: 0.5694865
  lightness: 0.796152
  brandStrength: 0.7321456
  brandColors:
    - '#1349A3'
    - '#E8631E'
    - '#000001'
    - '#BABCC8'
    - '#FCFFFF'
  rhythmicContrast: 0.8547339
typography_spectrum: 0.2455197
name: JamaarEverett
